alter table D06_ANAGRAFE_CARRIERA rename to D07_ANAGRAFE_CARRIERA;
alter table D06_ANAGRAFE_QUALIFICA rename to D07_ANAGRAFE_QUALIFICA;
alter table D06_ANAGRAFE_UNITA_ORGANIZZATIVE rename to D07_ANAGRAFE_UNITA_ORGANIZZATIVE;
alter table D06_ASSEGNAZIONE_UO rename to D07_ASSEGNAZIONE_UO;
alter table D06_DIPENDENTI rename to D07_DIPENDENTI;
alter table D06_MATRICOLE rename to D07_MATRICOLE;
alter table D06_ORGANICO rename to D07_ORGANICO;
alter table D06_PERSONE rename to D07_PERSONE;