drop table d07_matricole cascade constraints;
drop table d07_persone cascade constraints;
drop table d07_dipendenti cascade constraints;
drop table d07_anagrafe_carriera cascade constraints;
drop table d07_anagrafe_qualifica cascade constraints;
drop table d07_organico cascade constraints;
drop table d07_anagrafe_unita_organizzative cascade constraints;
drop table d07_assegnazione_uo cascade constraints;
-- create tables

create table d07_matricole (
    matricola    varchar2(5 char) not null
                 constraint d07_matricole_matricola_pk primary key
);

create table d07_persone (
    codice_persona    varchar2(5 char) not null
                      constraint  d07_persone_codice_persona_pk primary key,
    cognome           varchar2(50 char) not null,
    nome              varchar2(50 char) not null,
    data_nascita      varchar2(8 char) not null
);



create table d07_dipendenti (
    matricola          varchar2(5 char) 
                       constraint d07_dipendenti_matricola_fk 
                       references d07_matricole not null,
    codice_persona     varchar2(5 char)
                       constraint d07_dipendenti_codice_persona_fk
                       references d07_persone not null,
    tipo_dipendente    varchar2(1 char) not null,
    data_assunzione    varchar2(8 char) not null,
    data_cessazione    varchar2(8 char) not null,
    constraint  d07_dipendenti_pk primary key (matricola,data_assunzione)
);



create table d07_anagrafe_carriera (
    carriera       varchar2(1 char) not null
                   constraint  d07_anagrafe_carriera_carriera_pk primary key,
    descrizione    varchar2(20 char) not null
);



create table d07_anagrafe_qualifica (
    qualifica         varchar2(5 char) not null
                      constraint  d07_anagrafe_qualifica_qualifica_pk primary key,
    descrizione       varchar2(30 char) not null,
    carriera          varchar2(1 char)
                      constraint d07_anagrafe_qualifica_carriera_fk
                      references d07_anagrafe_carriera not null,
    tipo_qualifica    varchar2(1 char) not null,
    dirigente         varchar2(1 char) not null
);



create table d07_organico (
    matricola              varchar2(5 char) 
                           constraint d07_organico_matricola_fk 
                           references d07_matricole not null,
    qualifica              varchar2(5 char)
                           constraint d07_organico_qualifica_fk
                           references d07_anagrafe_qualifica not null,
    classe                 number not null,
    gradino                number not null,
    data_qualifica         varchar2(8 char) not null,
    data_gradino           varchar2(8 char) not null,
    data_fine_posizione    varchar2(8 char) not null,
    constraint  d07_organico_pk primary key (matricola,data_gradino)
);



create table d07_anagrafe_unita_organizzative (
    unita_org           varchar2(5 char) not null,
    tipo_org            varchar2(5 char) not null,
    desc_org            varchar2(80 char) not null,
    desc_breve          varchar2(30 char) not null,
    unita_superiore     varchar2(5 char) not null,
    ordine              varchar2(5 char) not null,
    data_i_posizione    varchar2(8 char) not null,
    data_f_posizione    varchar2(8 char) not null,
    constraint  d07_anagrafe_unita_organizzative_pk primary key (unita_org--,data_i_posizione
                                                               )
);



create table d07_assegnazione_uo (
    matricola           varchar2(5 char) 
                        constraint d07_d07_assegnazione_uo_matricola_fk 
                        references d07_matricole not null,
    unita_org           varchar2(5 char)
                        constraint d07_assegnazione_uo_unita_org_fk
                        references d07_anagrafe_unita_organizzative not null,
    sede                varchar2(30 char) not null,
    data_i_posizione    varchar2(8 char) not null,
    data_f_posizione    varchar2(8 char) not null,
    constraint  d07_assegnazione_uo_pk primary key (matricola,data_i_posizione)
);



-- Generated by Quick SQL undefined 11/3/2024, 20:11:22

/*
matricole
  matricola vc5 /pk

persone
  codice_persona vc5 /pk
  cognome        vc50 /nn
  nome           vc50 /nn
  data_nascita   vc8 /nn

dipendenti
  matricola vc5 /pk /fk matricola
  codice_persona vc5 /nn /fk persone
  tipo_dipendente vc1 /nn
  data_assunzione vc8 /pk
  data_cessazione vc8 /nn

anagrafe_carriera
  carriera vc1 /pk
  descrizione vc20 /nn

anagrafe_qualifica
  qualifica vc5 /pk  
  descrizione vc30 /nn
  carriera vc1 /nn /fk anagrafe_carriera
  tipo_qualifica vc1 /nn
  dirigente vc1 /nn

organico
  matricola vc5 /pk /fk matricola
  qualifica vc5 /nn /fk anagrafe_qualifica
  classe num /nn
  gradino num /nn
  data_qualifica vc8 /nn
  data_gradino vc8 /pk
  data_fine_posizione vc8 /nn

anagrafe_unita_organizzative
  unita_org vc5 /pk
  tipo_org vc5 /nn
  desc_org vc30 /nn
  desc_breve vc30 /nn
  unita_superiore vc5 /nn
  ordine vc5 /nn
  data_i_posizione vc8 /pk
  data_f_posizione vc8 /nn

assegnazione_uo
  matricola vc5 /pk /fk matricola
  unita_org vc5 /nn /fk anagrafe_unita_organizzative
  sede vc30 /nn
  data_i_posizione vc8 /pk
  data_f_posizione vc8 /nn


 Non-default options:
# settings = {"apex":"Y","db":"19c","drop":true,"prefix":"d07"}

*/