-- drop objects
drop table d08_error_lookup cascade constraints;

create table d08_error_lookup (
    id                             number generated by default on null as identity 
                                   constraint d08_error_lookup_id_pk primary key,
    constraint_name                varchar2(30 char) not null,
    message                        varchar2(4000 char) not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;


create or replace trigger d08_error_lookup_biu
    before insert or update 
    on d08_error_lookup
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d08_error_lookup_biu;
/

-- load data
 
 
/*

error_lookup 
  constraint_name vc30 /nn
  message vc4000 /nn



# settings = { prefix: "d08", onDelete: "RESTRICT", PK: "IDENTITY", semantics: "CHAR", auditCols: true, DB: "12C", drop: true, language: "EN", APEX: true }
*/
